
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------
package LenguajeJFlexCup;
/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DECIMAL = 6;
  public static final int MENOS = 8;
  public static final int POR = 9;
  public static final int ENTERO = 5;
  public static final int EOF = 0;
  public static final int MAS = 7;
  public static final int DIV = 10;
  public static final int ID = 4;
  public static final int IGUAL = 11;
  public static final int error = 1;
  public static final int GRANDE = 3;
  public static final int ALTO = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ALTO",
  "GRANDE",
  "ID",
  "ENTERO",
  "DECIMAL",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "IGUAL"
  };
}

